# Generated by Django 6.0.1 on 2026-01-07 04:54

import apps.song.models
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('song_title', models.CharField(max_length=250)),
                ('song', models.FileField(upload_to=apps.song.models.file_directory_path)),
                ('song_duration', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('song_extension', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('song', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='song.song')),
            ],
            options={
                'verbose_name_plural': 'RecentlyPlayed',
                'ordering': ['-date_played'],
            },
        ),
        migrations.CreateModel(
            name='SongLikedBy',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_likes', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='song.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name_plural': 'SongsLikedBy',
                'ordering': ['-date_likes'],
            },
        ),
    ]
