# Generated by Django 6.0.1 on 2026-01-07 04:54

import apps.album.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singer', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=25)),
                ('album_image', models.ImageField(upload_to=apps.album.models.file_directory_path)),
                ('album_bio', models.CharField(max_length=500)),
                ('album_info', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('album_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.singer')),
            ],
            options={
                'ordering': ['-date_created', 'album_name'],
            },
        ),
        migrations.CreateModel(
            name='AlbumLikedBy',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_subscribed', models.DateField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name_plural': 'AlbumsLikedBy',
                'ordering': ['-date_subscribed'],
            },
        ),
    ]
