# Generated by Django 4.1.3 on 2023-01-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestent',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('reg_no', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContestName',
            fields=[
                ('contest_name', models.CharField(choices=[('PROJECT_EXHITION', 'PE'), ('PROGRAMMING_CONTEST', 'PC'), ('IT_QUIZ', 'ITQ')], default='PC', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('contest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contestname')),
            ],
        ),
        migrations.CreateModel(
            name='TeamContestent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contestent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
