# Generated by Django 4.1.2 on 2022-10-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='singer/')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='singer/')),
                ('about', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('extension', models.CharField(choices=[('mp3', 'mp3'), ('wav', 'wav'), ('wma', 'wma'), ('m4a', 'm4a')], max_length=4)),
                ('music_file', models.FileField(upload_to='music/')),
                ('duration', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.singer'),
        ),
    ]
