# Generated by Django 4.1.2 on 2022-10-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
