# Generated by Django 4.1.2 on 2022-10-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_songs_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.album'),
        ),
    ]
