# Generated by Django 4.1.2 on 2022-10-22 17:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_song_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='logo/profile.jpg', upload_to=main.models.album_directory_path),
        ),
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.ImageField(default='logo/profile.jpg', upload_to=main.models.singer_directory_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='music_file',
            field=models.FileField(upload_to=main.models.file_directory_path),
        ),
    ]
