# Generated by Django 4.1.2 on 2022-10-10 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(default='logo/cover.png', upload_to='Cover')),
                ('profile_photo', models.ImageField(default='logo/profile.jpg', upload_to='Profile')),
                ('user_type', models.CharField(choices=[('Pri', 'Premium'), ('Reg', 'Regular')], default='Reg', max_length=4)),
                ('liked_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.songs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
