# Generated by Django 4.1.2 on 2022-10-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_songs_album'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_song',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_song',
            field=models.ManyToManyField(blank=True, null=True, to='main.songs'),
        ),
    ]
