# Generated by Django 4.1.2 on 2022-10-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_song_liked_by'),
        ('user', '0002_remove_profile_liked_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_song',
            field=models.ManyToManyField(to='main.song'),
        ),
    ]
