# Generated by Django 4.1.2 on 2022-10-22 15:31

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='logo/cover.png', upload_to=user.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='logo/profile.png', upload_to=user.models.user_directory_path),
        ),
    ]
