# Generated by Django 4.1.2 on 2022-10-22 15:49

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('user', '0004_alter_profile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_song',
            field=models.ManyToManyField(to='main.songs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='logo/profile.jpg', upload_to=user.models.user_directory_path),
        ),
    ]
